///////////////////////////////////////////////////////////////////////////////
// MovingMaterialSim.h
#pragma once

#include "RotaryCutterTwinInterfaces.h"

class CMovingMaterialSim
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CMovingMaterialSim();
	virtual	~CMovingMaterialSim();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	MovingMaterialSimParameter m_Parameter;
	MovingMaterialSimInputs m_Inputs;
	MovingMaterialSimOutputs m_Outputs;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>

private:
	// Real-Time Simulation State Variables
	ULONG m_simCycleCounter;     // Tracks task execution cycles
	bool  m_materialPresent;     // Internal status tracking of the virtual workpiece
};
