///////////////////////////////////////////////////////////////////////////////
// MovingMaterialSim.cpp
#include "TcPch.h"
#pragma hdrstop

#include "MovingMaterialSim.h"
#include "RotaryCutterTwinVersion.h"

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CMovingMaterialSim
BEGIN_INTERFACE_MAP(CMovingMaterialSim)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_IPERSIST_LIB(CMovingMaterialSim, VID_RotaryCutterTwin, CID_RotaryCutterTwinCMovingMaterialSim)
IMPLEMENT_ITCOMOBJECT(CMovingMaterialSim)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CMovingMaterialSim)
IMPLEMENT_ITCADI(CMovingMaterialSim)
IMPLEMENT_ITCWATCHSOURCE(CMovingMaterialSim)

///////////////////////////////////////////////////////////////////////////////
// Set parameters of CMovingMaterialSim 
BEGIN_SETOBJPARA_MAP(CMovingMaterialSim)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_MovingMaterialSimParameter, m_Parameter)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CMovingMaterialSim 
BEGIN_GETOBJPARA_MAP(CMovingMaterialSim)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_MovingMaterialSimParameter, m_Parameter)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CMovingMaterialSim
BEGIN_OBJPARAWATCH_MAP(CMovingMaterialSim)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CMovingMaterialSim
BEGIN_OBJDATAAREA_MAP(CMovingMaterialSim)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_MovingMaterialSimInputs, m_Inputs)
	OBJDATAAREA_VALUE(ADI_MovingMaterialSimOutputs, m_Outputs)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()

///////////////////////////////////////////////////////////////////////////////
CMovingMaterialSim::CMovingMaterialSim()
	: m_Trace(m_TraceLevelMax, m_spSrv)
	, m_simCycleCounter(0)
	, m_materialPresent(false)
{
///<AutoGeneratedContent id="MemberInitialization">
	m_TraceLevelMax = tlAlways;
	memset(&m_Parameter, 0, sizeof(m_Parameter));
	memset(&m_Inputs, 0, sizeof(m_Inputs));
	memset(&m_Outputs, 0, sizeof(m_Outputs));
///</AutoGeneratedContent>
}

CMovingMaterialSim::~CMovingMaterialSim()
{
}

///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CMovingMaterialSim)

HRESULT CMovingMaterialSim::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA_STR());
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	// Reset simulation variables on initialization
	m_simCycleCounter = 0;
	m_materialPresent = false;

	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

HRESULT CMovingMaterialSim::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());
	HRESULT hr = S_OK;

	hr = FAILED(hr) ? hr : AddModuleToCaller();
	if (FAILED(hr))
	{
		RemoveModuleFromCaller();
	}

	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

HRESULT CMovingMaterialSim::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());
	HRESULT hr = S_OK;
	RemoveModuleFromCaller();
	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

HRESULT CMovingMaterialSim::SetObjStateSP()
{
	HRESULT hr = S_OK;
	m_Trace.Log(tlVerbose, FENTERA_STR());
	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// Deterministic Real-Time Simulation Loop
///////////////////////////////////////////////////////////////////////////////
///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CMovingMaterialSim::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	// 1. Increment the real-time execution cycle counter
	m_simCycleCounter++;

	// 2. Material Arrival Logic: Trigger a new piece every 3000 cycles (e.g., 3 seconds)
	if (m_simCycleCounter >= 3000)
	{
		m_materialPresent = true;
		m_simCycleCounter = 0; // Reset tracking period
	}

	// 3. Knife Interaction Logic: If PLC outputs Sync cutting command, material is cut and cleared
	if (m_materialPresent && m_Inputs.bSyncCommand)
	{
		m_materialPresent = false;
	}

	// 4. Feed back to PLC: Update the physical mapping output structure
	m_Outputs.bSimulationInput = m_materialPresent;

	return hr;
}
///</AutoGeneratedContent>

///////////////////////////////////////////////////////////////////////////////
HRESULT CMovingMaterialSim::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());
	HRESULT hr = S_OK;
	if (m_spCyclicCaller.HasOID())
	{
		if (SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)))
		{
			if (FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))))
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID;
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}
	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

VOID CMovingMaterialSim::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());
	if (m_spCyclicCaller)
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller = NULL;
	m_Trace.Log(tlVerbose, FLEAVEA_STR());
}
