///////////////////////////////////////////////////////////////////////////////
// RotaryCutterTwinServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_RotaryCutterTwin = 0x3F000000;
#define SRVNAME_ROTARYCUTTERTWIN "RotaryCutterTwin"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_RotaryCutterTwinCMovingMaterialSim = {0xd505c43e,0xe349,0x41a5,{0x9c,0x51,0xa4,0x44,0x08,0xe0,0x74,0xf8}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_MovingMaterialSimInputs 0
#define ADI_MovingMaterialSimOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_MovingMaterialSimParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _MovingMaterialSimParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} MovingMaterialSimParameter, *PMovingMaterialSimParameter;

#pragma pack(push,1)
typedef struct _MovingMaterialSimInputs
{
	bool bSyncCommand;
} MovingMaterialSimInputs, *PMovingMaterialSimInputs;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _MovingMaterialSimOutputs
{
	bool bSimulationInput;
} MovingMaterialSimOutputs, *PMovingMaterialSimOutputs;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
