///////////////////////////////////////////////////////////////////////////////
// RotaryCutterTwinClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "RotaryCutterTwinClassFactory.h"
#include "RotaryCutterTwinServices.h"
#include "RotaryCutterTwinVersion.h"
#include "MovingMaterialSim.h"

BEGIN_CLASS_MAP(CRotaryCutterTwinClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_RotaryCutterTwin, CID_RotaryCutterTwinCMovingMaterialSim, SRVNAME_ROTARYCUTTERTWIN "!CMovingMaterialSim", CMovingMaterialSim)
///</AutoGeneratedContent>
END_CLASS_MAP()

CRotaryCutterTwinClassFactory::CRotaryCutterTwinClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_ROTARYCUTTERTWIN));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(RotaryCutterTwin));
#endif //defined(TCDBG_UNIT_VERSION)
}

