///////////////////////////////////////////////////////////////////////////////
// RotaryCutterTwinInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "RotaryCutterTwinServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
